### PR TITLE
Tfti2024 s2 branch

### PR DESCRIPTION
**Pull request by Smilyy**
Added a TFTI 2024 S2 event and some event photos. Check here: https://www.comssa.org.au/events 
Contact: Laura777881 @Discord

### CODE REVIEW

**Comment by s3ansh33p** [comment]
I have made some suggestions - see [commits here](https://github.com/s3ansh33p/comssa.github.io/commits/laura-suggestions/) 
- Mainly compressing the images by a factor of 10 (~1MB to ~100KB each).
- Renamed the image function from `tfti2024_S2` to `s2tfti2024` to be more consistent with other carousels.
- We also use yarn instead of npm/package-lock.json to manage packages, so I have removed the package-lock.json file.
- Continued updating some packages and checked that everything works.

**Review by s3ansh33p — CHANGES_REQUESTED** [review]
Please see my comments / linked suggestions
The actual code changes itself all worked :)

**Comment by Smilyy** [comment]
> I have made some suggestions - see [commits here](https://github.com/s3ansh33p/comssa.github.io/commits/laura-suggestions/)
> 
> * Mainly compressing the images by a factor of 10 (~1MB to ~100KB each).
> * Renamed the image function from `tfti2024_S2` to `s2tfti2024` to be more consistent with other carousels.
> * We also use yarn instead of npm/package-lock.json to manage packages, so I have removed the package-lock.json file.
> * Continued updating some packages and checked that everything works.

1. Downscale done.
2. Rename done.
3. Thanks for the reminder! 
4. Tested on yarn, also worked.

**Comment by s3ansh33p** [comment]
Thanks Laura - I will take a closer look later.
Can you please remove the pages/events/.index.vue.swp and package-lock.json files as well

**Comment by Smilyy** [comment]
> Thanks Laura - I will take a closer look later. Can you please remove the pages/events/.index.vue.swp and package-lock.json files as well

All done. Salute.

**Review by s3ansh33p — APPROVED** [review]
Thanks for making those changes Laura :)

**Pull request merged**
